### ISSUE TITLE
Pull fails on S4H 2021

### ISSUE THREAD

**Issue by fabianlupa** [SAP-samples/abap-platform-refscen-flight#11]
Hello,

I am trying to install the repo on a S/4HANA 2021 on premise system. I am using the branch ABAP-platform-2021 but it fails with some database tables:

![image](https://user-images.githubusercontent.com/5270359/214323725-fe7fbf32-2542-4c33-b565-f3444f5bdbea.png)

![image](https://user-images.githubusercontent.com/5270359/214323886-a37b8caa-0040-45a9-92d9-c01b2e653558.png)

![image](https://user-images.githubusercontent.com/5270359/214323928-8f004db2-2cc8-470a-a160-985412c27060.png)

Can you tell me how to resolve the issue? I set up the /DMO/ namespace as stated in the readme using the repair license and role consumer. However, the error message indicates that because it is consumer the field names may not be as they are?

**Comment by fabianlupa** [comment]
@MarinaBlank Any idea on how to solve the issue?

**Comment by MarinaBlank** [comment]
Hi Fabian, 
I was not able to reproduce the issue on my S/4HANA 2021 on premise system. 
For further analysis, please open a ticket on component BC-SRV-NWD-XBR with your system details. 

Thanks and best regards, 
Marina

**Comment by fabianlupa** [comment]
Hi Marina, thanks for your response, I created an incident.

**Comment by fabianlupa** [comment]
Hello again,

after dropping 3 tables on database level and repairing some CDS views the install was successful. Thanks!
