### ISSUE TITLE
Activation fails on ABAP Cloud instance

### ISSUE THREAD

**Issue by sedacrivity** [SAP-samples/abap-platform-refscen-flight#12]
When pulling the CLOUD branch into our ABAP cloud instance, the following errors and warnings occur:

![2023-02-15_105008](https://user-images.githubusercontent.com/14307554/218994847-69242893-2949-4e5c-a9cc-de7c627b5d2b.jpg)

The pull process is stuck now on object 56.

Kind Regards,

Steven

**Comment by MarinaBlank** [comment]
HI Steven, 

the issue might be related to a language version problem of the authorization field artefact. Please open a ticket on component BC-SEC-AUT-PFC with the given details. 

Thanks and best regards, 
Marina

**Comment by aleksei-belousov** [comment]
Names of any custom objects in SAP should be started with Z.
So, impossible to export from github to /DMO

**Comment by aleksei-belousov** [comment]
> Hi alexsei, if you are wokring on an ABAP environment instance on SAP BTP or S/4HANA Cloud, public edition you can directly download the repository with /DMO/ objects. If you are working on SAP S/4 HANA, on premise S/4 HANA Cloud, private edition, you have to set up the namespace first and then you can download the /DMO/ objects of this repository. See [README:](https://github.com/SAP-samples/abap-platform-refscen-flight/tree/main)

Hi Marina,
We works in S/4HANA Cloud, public edition
```
Use the abapGit plug-in to import the ABAP Flight Reference Scenario by executing the following steps:
 
1. In your ABAP cloud project, create the ABAP package /DMO/FLIGHT (using the superpackage /DMO/SAP) as the target package for the demo content to be downloaded (leave the suggested values unchanged when following the steps in the package creation wizard).

```
![image](https://user-images.githubusercontent.com/131857120/236440247-c9489991-9fe7-4d9b-9112-38d45c8c92e0.png)

"Namespace /DMO/ does not exist"

Besides that, there is the followng in README:
![image](https://user-images.githubusercontent.com/131857120/236442144-d58a52e8-c4f9-4944-96f8-a061bbd191d6.png)

**Comment by MarinaBlank** [comment]
Hi aleksei, 
thanks for the update. The restriction in the documentation is indeed wrong. The namespace /DMO/ should be available in S/4HANA Cloud, public edition systems. 

Please open a ticket on component BC-SRV-NWD-XBR with your system details, so we can look into this. 
Thanks and best regards, Marina

**Comment by aleksei-belousov** [comment]
Hi Marina,
Could you please explain, in brief, how to open a ticket on this issue.
Thank you.

Best regards,
Aleksei

**Comment by MarinaBlank** [comment]
Hi alexsei, 
 you can create incidents on the support launchpad: https://launchpad.support.sap.com/

Best regards, 
Marina

**Comment by aleksei-belousov** [comment]
Hi Marina,
Field 'System' is locked on the incident page.
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/131857120/11ec8929-3125-48df-8291-6adb28da50a8)
Best regards,
Aleksei

**Comment by MarinaBlank** [comment]
Hi alexsei, unfortunately I can't help you with that. Please refer to the support options for creating an incident [here](https://support.sap.com/en/my-support/product-support.html?anchorId=section_249481993) or get information in this video: https://www.youtube.com/watch?v=GtTTfB80Wb4&t=97s 

Best regards, 
Marina
