### ISSUE TITLE
Publish service failed -  'Test object cannot be created in foreign namespace'

### ISSUE THREAD

**Issue by itsmesabari** [SAP-samples/abap-platform-refscen-flight#14]
Hi ,

I have successfully pulled this repo to my on-premise system 2022.

I am facing issue in the below step - Publish failed with error 'Test object cannot be created in foreign namespace'
To generate service artifacts for the service bindings:
In each service binding, choose the button Publish or choose Publish local service endpoint in the top right corner of the editor.

Please suggest

![image](https://user-images.githubusercontent.com/42165579/226914522-78dd0274-1c9f-4a0f-a29e-3d7f343507fa.png)

I missed the below step and deleted the /DMO/ namespace locally by selecting the pop shown during pull request.
Do not delete the /DMO/ namespace locally because the pull operation will fail if no suiting namespace exists in your package.

Thanks,

**Comment by MarinaBlank** [comment]
Hi itsmesabari, 

Depending on the configuration of your client in the system, it is not possible to publish the service via the publish button in the service binding. Instead, you have to use Gateway tools to publish it. I recently included a note in the README file that addresses this issue. 
Please see [Service Binding - Service Transport](https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/b58a3c27df4e406f9335d4b346f6be04.html?state=DRAFT&version=202210.LATEST#%EE%81%B0-service-transport) for instructions on how to publish the service with Gateway Tools. 

Best regards, 
Marina

**Comment by itsmesabari** [comment]
Thanks @MarinaBlank  for the update.

Publish button is enabled, but we are getting error. Is there any setting we need to make in the system ? 
Please suggest.

**Comment by MarinaBlank** [comment]
Hi Itsemesabari, 

Publishing via the "Publish" button does not work. You have to use the gateway tools indicated in [Service Binding - Service Transport](
https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/b58a3c27df4e406f9335d4b346f6be04.html?version=202210.LATEST&q=Service%20Binding#%EE%81%B0-service-transport). 

Best regards, Marina
