### ISSUE TITLE
READ.me link for 1909 is broken

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [SAP-samples/abap-platform-refscen-flight#18]
On [main page](https://github.com/SAP-samples/abap-platform-refscen-flight) the link to [READ-ME](https://github.com/SAP-samples/abap-platform-refscen-flight/blob/ABAP-platform-1909/README.md) of branch ABAP-platform-1909 (Application Server ABAP 7.54) results in "404 - page not found" and the whole 1909 branch is gone, too.

**Comment by GeorgReichert1** [comment]
Hello Andrea,
we corrected the link to the branch. Thank you for reporting this issue.
Best regards
Georg

**Comment by AndreaBorgia-Abo** [comment]
removing the branch, however, is not cool

**Comment by GeorgReichert1** [comment]
Hello Andrea,
we did not remove the branch, we just renamed it to "ABAP-platform-2019".
Best regards
Georg

**Comment by AndreaBorgia-Abo** [comment]
when it comes to git, that looks like a removal since there is no redirect
thanks for the info, I'll try again in my A4H minisap, over and out

**Comment by julieplummer20** [comment]
Hi Georg,
I've just tested the link on "[main page](https://github.com/SAP-samples/abap-platform-refscen-flight) the link to [READ-ME](https://github.com/SAP-samples/abap-platform-refscen-flight/blob/ABAP-platform-1909/README.md) of branch ABAP-platform-1909";
I'm getting the same error as Andrea. 

Please advise.
Thanks a lot,
Julie Plummer.
ABAP PM.

**Comment by GeorgReichert1** [comment]
Hi Julie,
I updated the link. Thanks for reporting.
Best regards
Georg

**Comment by julieplummer20** [comment]
Hi Georg,
Thanks a lot for this fast response.
Best wishes, 
JUlie.
