### ISSUE TITLE
[7.58] dmo/cl_flight_data_generator dumps due to missing number range definitions 

### ISSUE THREAD

**Issue by Incho77** [SAP-samples/abap-platform-refscen-flight#26]
Class **dmo/cl_flight_data_generator** dumps generated dumps due to missing number range definitions (in release 7.58).

After debugging and manually creating the following number ranges (based on TRL), the generator program worked fine:
- DMO/AGNCY Agency IDs
- DMO/SUPPL Supplement
- DMO/TRAVL Travel
- DMO/TRV_M Travel_ID number range object

These objects should be also part of the GIT repository.

**Comment by VolkerDrees** [comment]
Hello Peter,
all 4 number range objects are contained in the repository / 2023 branch, see:

https://github.com/SAP-samples/abap-platform-refscen-flight/blob/ABAP-platform-2023/src/legacy/%23dmo%23agncy.nrob.xml
https://github.com/SAP-samples/abap-platform-refscen-flight/blob/ABAP-platform-2023/src/reuse/supplement/%23dmo%23suppl.nrob.xml
https://github.com/SAP-samples/abap-platform-refscen-flight/blob/ABAP-platform-2023/src/legacy/%23dmo%23travl.nrob.xml
https://github.com/SAP-samples/abap-platform-refscen-flight/blob/ABAP-platform-2023/src/managed/%23dmo%23trv_m.nrob.xml

Maybe there was an issue with ZABAPGIT and the import of the number range objects did not happen?
Best Regards, Volker
