### ISSUE TITLE
Job canceled after system exception ERROR_MESSAGE

### ISSUE THREAD

**Issue by Tediace** [SAP-samples/abap-platform-refscen-flight#28]
ABAP Object import log: Pull aborted: Repository pull aborted - Job canceled after system exception ERROR_MESSAGE
 Please check status and message for all imported ABAP objects

When iam trying to pull the branch ABAP-Cloud i got the error messages
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/43319929/b9a661ca-d5cc-4374-a4ed-c8627362d0e3)

Can anyone help me with this issue...

**Comment by VolkerDrees** [comment]
Hello Tedi,
it looks like, that no artifact was imported at all.
Can you check if the structure package **/DMO/SAP** exists in your cloud system?  If not, I assume the namespace /DMO/ is also missing.  
In this case please create a support ticket on component:  BC-SRV-APS-EXT-SL
Best Regards, Volker

**Comment by Tediace** [comment]
Hello Volrker,
Thank you reply my question...
I have an structure package /DMO/SAP and iam using software component BC-SRV-APS-EXT-SL
but i still got that error
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/43319929/2574d3ef-e78a-481c-9d26-6d040b56d83d)

**Comment by VolkerDrees** [comment]
Hello Tedi,
that's good if the structure package /DMO/SAP is present in your cloud system.
In this case, please create the package /DMO/FLIGHT as a sub-package of /DMO/SAP and proceed as explained here: https://github.com/SAP-samples/abap-platform-refscen-flight/tree/ABAP-platform-cloud?tab=readme-ov-file#download 
Btw: you can't import the demo content into a Z-Package as it violates the namespace.
Best Regards, Volker

**Comment by Tediace** [comment]
Hello Volker,
before i was trying to create package /DMO/SAP with super package /DMO/SAP..
but, i got an validation error look like this
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/43319929/d269c0ce-a7f2-495a-9852-92e6e21ba2da)
Regards,
Tedi Yudi Permadi

**Comment by VolkerDrees** [comment]
Hello Tedi,
oh - you are trying to import the reference scenario into the Public Trial environment. That doesn't work. 
The landscape is centrally maintained, and the package /DMO/FLIGHT with the reference scenarios contained should already be there. Can you check that?
Best Regards, Volker

**Comment by Tediace** [comment]
Hello Volker,
I understand right now... that why I can't create package /DMO/FLIGHT
there is no package name /DMO/FLIGHT but there similar package name /DMO/GPTFLT
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/43319929/dcd861c7-b750-4ff4-b637-b0aee3743f1c)
but I think /DMO/GPTFLT is what you mentioned.
Regards,
Tedi

**Comment by VolkerDrees** [comment]
Hello Tedi,
no. That doesn't look correct. I need to check this with the colleagues responsible for the ABAP Trial environment. I'll get back to you once I have an update.
Best Regards, Volker

**Comment by Tediace** [comment]
Hello Volker,
I appreciate for that
Thank you so much for helping me
Best Regards,
Tedi

**Comment by anfisc** [comment]
Hi Tedi,
there is unfortunately a problem with one of our shared instances where the import of the /DMO/ Flight sample runs into problems. 
If you want to test the /DMO/ sample I suggest you delete your ABAP Trial instance in your SAP BTP Trial and start the booster once again. 
This will mean that you will get a new user on another shared trial system where the /DMO/ sample should be present.
You can export any objects you have created using the abapGIT plugin into a private GitHub repository and pull it from there in the new instance.
Sorry for any inconvenience this may cause.
Kind regards,
Andre

**Comment by Tediace** [comment]
Hello Andre,
Thank you for the response Andre
that is a good explanation... I will try again after my trial is over and create a new account for that
Thank you again for Volker and Andre for helping with this issue

Best Regards,
Tedi

**Comment by Tediace** [comment]
Hello Andre,
It works now when trying to recreate a new ABAP instance

![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/43319929/d0567500-36bb-447d-bff8-21990a299e7b)

Best regards,
Tedi
