### ISSUE TITLE
Error when importing repository to BTP ABAP Cloud Free Tier

### ISSUE THREAD

**Issue by edemey** [SAP-samples/abap-platform-refscen-flight#29]
Hi,
I am getting an error when selecting the repository using the following link:
https://github.com/SAP-samples/abap-platform-refscen-flight/tree/ABAP-platform-cloud
![13-01-2024_18-44-37](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/15869538/bbfe82d4-10ac-4b8f-ba56-06ba1ae5c860)
Could you please help?
BR, Eddy

**Comment by VolkerDrees** [comment]
Hello Eddy,
you are using the browser URL. Instead you need to use the git URL:  https://github.com/SAP-samples/abap-platform-refscen-flight.git  as mentioned in step 4 of the download guide (https://github.com/SAP-samples/abap-platform-refscen-flight/tree/ABAP-platform-cloud?tab=readme-ov-file#download).

Best Regards, Volker

**Comment by edemey** [comment]
Hi Volker,
thanks...
With the link
https://github.com/SAP-samples/abap-platform-refscen-flight.git
the pull seems to be successfull but the package /DMO/FLIGHT is empty.
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/15869538/0140da29-ef8b-443b-881d-a9573a48fc8d)
![image](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/15869538/dc8c38b0-0e3b-4faa-91a1-7a1bdfdf6f60)
Could you again have a look?
BR, Eddy

**Comment by VolkerDrees** [comment]
Hello Eddy,
please follow the guide: https://github.com/SAP-samples/abap-platform-refscen-flight/tree/ABAP-platform-cloud#download  step 5 explains to choose the branch "ABAP-platform-cloud".  In your case I assume you have selected the "main" branch, which is empty (on purpose).

Best Regards, Volker

**Comment by edemey** [comment]
Thanks Volker....
I am a newby in ABAPGit for ADT. Now the repository is pulled.
BR, Eddy
