### ISSUE TITLE
Unable to connect https://github.com/SAP/abap-platform-refscen-flight.git   HTTP Client error

### ISSUE THREAD

**Issue by hakimred** [SAP-samples/abap-platform-refscen-flight#30]
Hello
I am trying to connec to https://github.com/SAP/abap-platform-refscen-flight.git from zabapgit_standalone program from S/4 HANA system. I am getting the error "Error while creating HTTP Client". PFA Screenshot. 
![abapgit error](https://github.com/SAP-samples/abap-platform-refscen-flight/assets/35043777/2e16014c-f89d-401e-9d2a-0b31b555ff85)

Regards,
Abdul Hakim

**Comment by VolkerDrees** [comment]
Hello Abdul, 
this seems to be an issue with the ZABAPGIT tooling itself.
We can only provide support for the repo itself, but not for the tooling. I'd propose that you raise your issue here: https://github.com/abapGit/abapGit 
Best Regards, Volker

**Comment by hakimred** [comment]
> Hello Abdul, this seems to be an issue with the ZABAPGIT tooling itself. We can only provide support for the repo itself, but not for the tooling. I'd propose that you raise your issue here: https://github.com/abapGit/abapGit Best Regards, Volker

Hello Volker, Thanks for the response. I have reported the issue to abapgit team. QQ is there way i can download the content from this repository and upload into my system without using ZABAPGIT? Please let me know.

Regards,
Abdul Hakim
