### ISSUE TITLE
ABAP BTP Branch pulled with error "No authorization to change authorization field &/DMO/CNTRY&." in Free Tier

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/abap-platform-refscen-flight#9]
Hello SAP ABAP Reference Scenario Team,

I'm the admin user of my SAP BTP Free Tier ABAP Environment. I've just tried to pull the updates from the [https://github.com/SAP-samples/abap-platform-refscen-flight/tree/BTP-ABAP](BTP-ABAP) branch. But I get this error message: 

```
/DMO/CNTRY | AUTH | E | No authorization to change authorization field &/DMO/CNTRY&.
```

For reference also this screenshot:

![Screenshot 2022-10-15 at 10 11 50](https://user-images.githubusercontent.com/2639535/195976631-e510b271-d154-46f8-a577-2f389d60ba45.png)

I've also activated the  Authorization Trace for my user but I can't find any failed authorization checks there.

Best Regards
Gregor

**Comment by VolkerDrees** [comment]
Hello Gregor,
the error can be ignored. See: https://github.com/SAP-samples/abap-platform-refscen-flight/tree/BTP-ABAP#download  point nr. 8.

Best Regards, 
Volker

**Comment by gregorwolf** [comment]
To bad that the GitHub search doesn't find the README when searching for /DMO/CNTRY. But it now finds this issue.
